version: '3.8'

services:
  backend-api:
    build: ./AWS-IAM-backend
    container_name: cloudlens-backend
    ports:
      - "8000:8000"
    env_file:
      - ./AWS-IAM-backend/.env
    volumes:
      - ./AWS-IAM-backend:/app

  frontend-ui:
    build: ./AWS-IAM-frontend
    container_name: cloudlens-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend-api
    volumes:
      - ./AWS-IAM-frontend:/app
      - /app/node_modules
